######################################################################
# Automatically generated by qmake (3.0) Thu Dec 1 10:32:07 2016
######################################################################

TEMPLATE = app
TARGET = Qt_test
INCLUDEPATH += .

# Input
HEADERS += heat_equation.h ui_heat_equation.h
FORMS += heat_equation.ui
SOURCES += heat_equation.cpp main.cpp
