######################################################################
# Automatically generated by qmake (2.01a) Sat Dec 10 15:43:34 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += heat_equation.h
FORMS += heat_equation.ui
SOURCES += heat_equation.cpp main.cpp
