######################################################################
# Automatically generated by qmake (2.01a) Mon Dec 12 20:17:16 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += heat_equation.h
FORMS += heat_equation.ui
SOURCES += heat_equation.cpp main.cpp
